name: build

permissions: read-all

on:
  push:
  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  synthesis:
    runs-on: ubuntu-latest
    container: raetro/quartus:17.1
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run compilation flow
        run: quartus_sh --flow compile fpga-atlas-soc-divider.qpf

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: OutputFiles.zip
          path: output_files/
