name: verible

permissions: read-all

on:
  push:
  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: verible
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Verible
        uses: chipsalliance/verible-linter-action@68df99cc51c953dcf727901905ab1d7b76f7338c
        with:
          fail_on_error: true
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate tests summary
        if: ${{ always() }}
        run: |
          cat -n verible-verilog-lint.log >> "$GITHUB_STEP_SUMMARY"
